import { GROOMING_ICON } from './grooming-icon.js';
import { observeUI } from './ui-lifecycle.js';
import './v26-hotfix.js';
(() => {
  const healthIcons={
    'Vaccinations':'<svg viewBox="0 0 256 256" fill="currentColor"><path d="m72 184 96-96 24 24-96 96H72v-24Z" opacity=".2"/><path d="m216 64-24-24a8 8 0 0 0-11 11l6 7-25 25-13-13a8 8 0 0 0-11 11l7 7-79 79a8 8 0 0 0-2 5v20H44a8 8 0 0 0 0 16h20v20a8 8 0 0 0 16 0v-20h20a8 8 0 0 0 6-2l79-79 7 7a8 8 0 1 0 11-11l-13-13 25-25 7 6a8 8 0 0 0 11-11ZM97 192H80v-17l76-76 17 17Z"/></svg>',
    'Deworming':'<svg viewBox="0 0 256 256" fill="currentColor"><path d="M40 144c0-44 36-80 80-80h48a48 48 0 0 1 0 96h-40a24 24 0 0 0-24 24v16H72v-16c0-22 18-40 40-40h56a32 32 0 0 0 0-64h-48a64 64 0 0 0-64 64Z" opacity=".2"/><path d="M168 56h-48a88 88 0 0 0-88 88 8 8 0 0 0 16 0 72 72 0 0 1 72-72h48a40 40 0 0 1 0 80h-56a48 48 0 0 0-48 48 8 8 0 0 0 16 0 32 32 0 0 1 32-32h56a56 56 0 0 0 0-112Z"/></svg>',
    'Flea & Tick':'<svg viewBox="0 0 256 256" fill="currentColor"><path d="M192 120v48a64 64 0 0 1-128 0v-48a64 64 0 0 1 128 0Z" opacity=".2"/><path d="M224 160h-24v-32h24a8 8 0 0 0 0-16h-25a72 72 0 0 0-17-36l17-17a8 8 0 0 0-11-11l-18 17a72 72 0 0 0-84 0L68 48a8 8 0 0 0-11 11l17 17a72 72 0 0 0-17 36H32a8 8 0 0 0 0 16h24v32H32a8 8 0 0 0 0 16h25a72 72 0 0 0 142 0h25a8 8 0 0 0 0-16Zm-40 8a56 56 0 0 1-112 0v-48a56 56 0 0 1 112 0Z"/></svg>'
  };
  const css=`
  .rail__theme{position:relative;overflow:hidden}.tg{display:block;overflow:visible}.tg__rays{transform-origin:12px 12px;transition:transform .5s cubic-bezier(.2,.8,.2,1),opacity .28s}.tg__disc{transform-origin:12px 12px;transition:transform .45s cubic-bezier(.2,.8,.2,1)}.tg__cut{fill:var(--paper);transform:translate(10px,-10px);transition:transform .5s cubic-bezier(.2,.8,.2,1),fill .35s}.tg[data-theme="dark"] .tg__rays{transform:rotate(35deg) scale(.55);opacity:0}.tg[data-theme="dark"] .tg__disc{transform:scale(.88)}.tg[data-theme="dark"] .tg__cut{transform:translate(4px,-3px);fill:var(--paper)}
  ::view-transition-old(root),::view-transition-new(root){animation:none;mix-blend-mode:normal}::view-transition-new(root){z-index:99999}::view-transition-old(root){z-index:1}
  @media(hover:hover) and (pointer:fine){.bento__card .bento__arrow,.bento__card [class*="arrow"],.bento__card [class*="external"]{opacity:0;transform:translate(-5px,5px) scale(.9);transition:.24s}.bento__card:hover .bento__arrow,.bento__card:hover [class*="arrow"],.bento__card:hover [class*="external"]{opacity:1;transform:none}.bento__card{transition:transform .28s cubic-bezier(.2,.8,.2,1),box-shadow .28s}.bento__card:hover{transform:translateY(-3px)}}
  .bento__card[href="/health"] .bento__desc{max-width:88%;line-height:1.38;margin-bottom:54px}.bento__card[href="/health"] .bento__chips{height:38px;bottom:12px}.bento__card[href="/health"] .bento__chip{gap:5px;white-space:nowrap}.bento__card[href="/health"] .bento__chip svg{width:14px;height:14px;flex:0 0 14px;color:var(--ink)}
  .home__promo-card{padding:0!important;display:block!important;position:relative!important;overflow:hidden!important;background:transparent!important}.home__promo-viewport{height:100%!important;min-height:174px!important;border-radius:inherit!important;overflow-x:auto!important}.home__promo-track{height:100%!important}.home__promo-slide{height:100%!important;min-height:174px!important;border-radius:inherit!important;padding:27px 34px!important;background:linear-gradient(112deg,rgba(255,255,255,.78),rgba(226,236,255,.72))!important;box-shadow:none!important;align-content:center!important;gap:4px!important}.home__promo-label{position:absolute;top:20px;left:28px;color:var(--ink);font-size:13px;font-weight:700}.home__promo-slide>span{margin-top:17px}.home__promo-head{position:absolute!important;inset:0!important;z-index:8!important;pointer-events:none!important;padding:0!important}.home__promo-head>strong{display:none!important}.home__promo-controls{position:absolute!important;right:16px!important;top:15px!important;pointer-events:auto!important;opacity:0;transform:translateY(-3px);transition:.22s}.home__promo-card:hover .home__promo-controls,.home__promo-card:focus-within .home__promo-controls{opacity:1;transform:none}.home__promo-dots{z-index:9!important}[data-theme="dark"] .home__promo-slide{background:linear-gradient(112deg,rgba(21,43,78,.88),rgba(8,27,55,.82))!important}
  .pet-workspace-v25{margin-top:14px;padding:10px;border-radius:25px;background:rgba(255,255,255,.42);box-shadow:inset 0 0 0 1px rgba(11,30,63,.12),0 18px 50px -42px rgba(6,12,26,.45);backdrop-filter:blur(16px)}.pet-workspace-v25>.pet-tabs{width:max-content;max-width:100%;margin:0 0 12px;padding:6px;border-radius:18px;background:rgba(226,234,247,.68);box-shadow:inset 0 0 0 1px rgba(11,30,63,.1);overflow:auto;scrollbar-width:none}.pet-workspace-v25>.pet-tabs button{border-radius:13px!important;min-height:38px;padding:0 14px!important}.pet-workspace-v25>.pet-tabs button.is-active{background:#07101f!important;color:#fff!important;box-shadow:0 8px 20px -12px rgba(7,16,31,.7)}[data-theme="dark"] .pet-workspace-v25{background:rgba(255,255,255,.045)}
  .about-contact-shell{display:grid;grid-template-columns:minmax(280px,.78fr) minmax(420px,1.45fr);gap:20px;padding:18px;border-radius:30px;background:linear-gradient(115deg,rgba(255,255,255,.72),rgba(220,233,255,.78));box-shadow:inset 0 0 0 1px rgba(11,30,63,.13)}.about-faq-panel{padding:24px 22px;border-radius:24px;background:#07101f;color:#f4f4ed}.about-faq-panel .clone-card__no{color:var(--orange)}.about-faq-panel h2{margin:8px 0 15px;font-size:24px;line-height:1.05}.about-faq-panel h2 span{color:#858c9b}.about-faq{border-top:1px solid rgba(255,255,255,.1)}.about-faq summary{list-style:none;cursor:pointer;padding:12px 0;display:flex;justify-content:space-between;gap:12px;font-size:11px;font-weight:700}.about-faq summary::-webkit-details-marker{display:none}.about-faq summary b{color:var(--orange);margin-right:12px}.about-faq p{margin:0;padding:0 0 13px 31px;color:#aeb6c5;font-size:10px;line-height:1.65}.about-email{display:inline-flex;margin-top:16px;padding:10px 13px;border-radius:999px;color:#fff;background:rgba(255,255,255,.06);box-shadow:inset 0 0 0 1px rgba(255,255,255,.13);font-size:10px}.about-form-panel{padding:22px;border-radius:24px;background:rgba(255,255,255,.76);box-shadow:inset 0 0 0 1px rgba(11,30,63,.16)}.about-form{display:grid;gap:13px}.about-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.about-form label{display:grid;gap:7px;color:#657086;font-size:9px;font-weight:700;letter-spacing:.08em}.about-form input,.about-form textarea{width:100%;border:0;outline:0;border-radius:14px;background:rgba(255,255,255,.72);box-shadow:inset 0 0 0 1px rgba(11,30,63,.22);padding:0 14px;color:var(--ink);font:500 12px/1.4 Poppins}.about-form input{height:43px}.about-form textarea{height:176px;padding-top:13px;resize:vertical}.about-form input:focus,.about-form textarea:focus{box-shadow:inset 0 0 0 2px var(--orange)}.about-submit-row{display:flex;align-items:center;gap:14px}.about-submit-row span{font-size:9px;color:var(--muted)}[data-theme="dark"] .about-contact-shell{background:linear-gradient(115deg,rgba(14,35,66,.84),rgba(8,23,48,.88))}[data-theme="dark"] .about-form-panel{background:rgba(255,255,255,.055)}[data-theme="dark"] .about-form input,[data-theme="dark"] .about-form textarea{background:rgba(255,255,255,.055);color:#f4f4ed}
  @media(max-width:900px){.home__promo-viewport,.home__promo-slide{min-height:132px!important}.home__promo-controls{opacity:1;transform:none}.home__promo-slide{padding:24px 22px!important}.home__promo-label{top:16px;left:20px}}@media(max-width:760px){.about-contact-shell{grid-template-columns:1fr;padding:10px}.about-form-grid{grid-template-columns:1fr}.about-form textarea{height:150px}.pet-workspace-v25{padding:7px}.pet-workspace-v25>.pet-tabs{width:100%}}
  `;
  const style=document.createElement('style'); style.id='branddemo-v25'; style.textContent=css; document.head.appendChild(style);

  function patchHome(){
    document.querySelectorAll('a[href="/grooming"] .ricon,a.bento__card[href="/grooming"] .bento__icon').forEach(el=>{if(!el.dataset.groomingReady){el.innerHTML=GROOMING_ICON;el.dataset.groomingReady="1"}});
    const health=document.querySelector('a.bento__card[href="/health"]');
    if(health&&!health.dataset.v25){ health.dataset.v25='1'; const d=health.querySelector('.bento__desc'); if(d)d.textContent='Vaccinations, preventives and care records.'; const chips=health.querySelector('.bento__chips'); if(chips)chips.innerHTML=Object.entries(healthIcons).map(([n,svg])=>`<span class="bento__chip" data-status="Saved">${svg}${n}</span>`).join(''); }
    const promo=document.querySelector('.home__promo-card'); if(promo&&!promo.dataset.v25){promo.dataset.v25='1';promo.querySelectorAll('.home__promo-slide').forEach(s=>s.insertAdjacentHTML('afterbegin','<b class="home__promo-label">Updates</b>'));}
  }
  function patchPets(){
    if(location.pathname!='/pets')return; const glass=document.querySelector('#main-content .clone-glass'); const tabs=glass?.querySelector(':scope > .pet-tabs'); if(!glass||!tabs||tabs.parentElement.classList.contains('pet-workspace-v25'))return; const wrap=document.createElement('div');wrap.className='pet-workspace-v25';tabs.before(wrap);wrap.appendChild(tabs);while(wrap.nextSibling)wrap.appendChild(wrap.nextSibling);
  }
  function patchAbout(){
    if(location.pathname!='/about')return; const main=document.querySelector('#main-content'); const page=main?.querySelector('.clone-page'); if(!page||page.dataset.v25)return; page.dataset.v25='1'; const old=page.querySelector('.clone-glass'); if(!old)return; old.outerHTML=`<div class="about-contact-shell"><section class="about-faq-panel"><div class="clone-card__no">FAQs</div><h2>Quick answers.<br><span>Still have one? Write below.</span></h2>${[['What is YourBrand?','One connected workspace for profiles, health, grooming, hotel stays, rewards and care history.'],['Can I keep more than one pet?','Yes. Records and appointments stay attached to each individual pet.'],['How do bookings work?','Choose a pet and service or stay dates, then save the request from YourBrand.'],['Where is my data stored?','This concept currently stores workspace data locally in your browser.']].map((f,i)=>`<details class="about-faq" ${i===0?'open':''}><summary><span><b>${String(i+1).padStart(2,'0')}</b>${f[0]}</span><i>⌄</i></summary><p>${f[1]}</p></details>`).join('')}<a class="about-email" href="mailto:hello@brickand.bond">hello@brickand.bond</a></section><section class="about-form-panel"><form class="about-form" data-about-contact><div class="about-form-grid"><label>FIRST NAME<input name="firstName" placeholder="Fur parent" required></label><label>LAST NAME<input name="lastName" placeholder="Last name" required></label></div><label>EMAIL<input type="email" name="email" placeholder="you@example.com" required></label><label>TELL US ABOUT YOUR PET CARE NEEDS<textarea name="message" placeholder="Grooming, hotel stay, health records, membership, or something else?" required></textarea></label><div class="about-submit-row"><button class="clone-btn" type="submit">Send message ↗</button><span>Your Brand.</span></div></form></section></div>`;
  }
  function patch(){patchHome();patchPets();patchAbout();}
  observeUI(patch);
  document.addEventListener('submit',e=>{const f=e.target.closest('[data-about-contact]');if(!f)return;e.preventDefault();const d=new FormData(f),subject=encodeURIComponent('YourBrand inquiry from '+d.get('firstName')),body=encodeURIComponent(`Name: ${d.get('firstName')} ${d.get('lastName')}\nEmail: ${d.get('email')}\n\n${d.get('message')}`);location.href=`mailto:hello@brickand.bond?subject=${subject}&body=${body}`;});
  document.addEventListener('click',e=>{const b=e.target.closest('.rail__theme');if(!b||b.dataset.v25click)return; if(!document.startViewTransition||matchMedia('(prefers-reduced-motion: reduce)').matches)return; e.preventDefault();e.stopImmediatePropagation();const next=document.documentElement.dataset.theme==='dark'?'light':'dark',r=b.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2,rad=Math.hypot(Math.max(x,innerWidth-x),Math.max(y,innerHeight-y));const vt=document.startViewTransition(()=>{document.documentElement.dataset.theme=next;b.setAttribute('aria-label',next==='dark'?'Switch to light theme':'Switch to dark theme');const tg=b.querySelector('.tg');if(tg)tg.dataset.theme=next;try{localStorage.setItem('tfa-theme',next)}catch{}window.dispatchEvent(new CustomEvent('themechange',{detail:{theme:next}}));});vt.ready.then(()=>document.documentElement.animate({clipPath:[`circle(0 at ${x}px ${y}px)`,`circle(${rad}px at ${x}px ${y}px)`]},{duration:620,easing:'cubic-bezier(.2,.8,.2,1)',pseudoElement:'::view-transition-new(root)'}));},true);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patch,{once:true});else patch();
})();