import { observeUI } from './ui-lifecycle.js';
(() => {
  const TYPES=['Vaccinations','Deworming','Flea & Tick','Allergy','Medication','Surgery','Condition','Vet Visit','Weight Record','Dental Care','Lab / Test Result','Other'];
  const ICONS={'Vaccinations':'syringe','Deworming':'worm','Flea & Tick':'bug','Allergy':'warning-circle','Medication':'pill','Surgery':'bandaids','Condition':'heartbeat','Vet Visit':'stethoscope','Weight Record':'scales','Dental Care':'tooth','Lab / Test Result':'test-tube','Other':'heart'};
  const STORE_KEY='brand-demo-workspace-v1';

  const css=`
  .home__promo-card{isolation:isolate!important;overflow:hidden!important;background:linear-gradient(112deg,rgba(255,255,255,.78),rgba(226,236,255,.72))!important;box-shadow:inset 0 0 0 1px rgba(11,30,63,.13),0 18px 45px -34px rgba(11,30,63,.35)!important}
  [data-theme="dark"] .home__promo-card{background:linear-gradient(112deg,rgba(21,43,78,.9),rgba(8,27,55,.88))!important}
  .home__promo-viewport,.home__promo-track,.home__promo-slide{background:transparent!important;box-shadow:none!important;border:0!important}
  .home__promo-slide{padding:54px 34px 26px!important;min-height:174px!important}
  .home__promo-slide>.home__promo-label,.home__promo-card>.home__promo-label{display:none!important}
  .home__promo-head .bento__title{display:block!important;position:relative!important;z-index:12!important}
  .home__promo-slide>span{margin-top:0!important}
  .home__promo-controls{z-index:15!important}

  .bento__card--about .bento__fan{top:62px!important;bottom:auto!important}
  .pet-health-add{overflow:visible!important;z-index:4!important}.pet-health-picker{position:relative!important;z-index:40!important;overflow:visible!important}.pet-health-picker>summary{cursor:pointer!important;pointer-events:auto!important;user-select:none!important;position:relative!important;z-index:42!important}.pet-health-picker[open] .pet-health-menu{display:grid!important;position:absolute!important;left:0!important;right:0!important;top:calc(100% + 8px)!important;z-index:99!important;max-height:270px!important;overflow:auto!important;background:var(--paper,#fbfbf7)!important;border-radius:16px!important;padding:8px!important;box-shadow:0 24px 55px -24px rgba(7,16,31,.55),inset 0 0 0 1px rgba(11,30,63,.14)!important}[data-theme="dark"] .pet-health-picker[open] .pet-health-menu{background:#10213a!important}.pet-health-option{pointer-events:auto!important;position:relative!important;z-index:100!important}
  .pet-record-type-select-wrap{grid-column:auto;display:grid;gap:7px;font-size:10px;font-weight:700;color:var(--muted)}.pet-record-type-select{appearance:none;background-image:linear-gradient(45deg,transparent 50%,currentColor 50%),linear-gradient(135deg,currentColor 50%,transparent 50%);background-position:calc(100% - 18px) 19px,calc(100% - 13px) 19px;background-size:5px 5px,5px 5px;background-repeat:no-repeat;padding-right:38px!important}.pet-record-custom{display:none}.pet-record-custom.is-visible{display:grid}

  .pet-profile-card{position:relative}.pet-photo-edit{position:absolute;right:20px;top:18px;z-index:4;border:0;border-radius:999px;padding:9px 12px;background:rgba(255,255,255,.94);box-shadow:0 8px 22px -12px rgba(7,16,31,.5),inset 0 0 0 1px rgba(11,30,63,.12);color:var(--ink);font:700 9px/1 Poppins;cursor:pointer;transition:transform .2s ease,box-shadow .2s ease}.pet-photo-edit:hover{transform:translateY(-1px);box-shadow:0 10px 26px -12px rgba(7,16,31,.58),inset 0 0 0 1px rgba(11,30,63,.15)}[data-theme="dark"] .pet-photo-edit{background:rgba(15,31,55,.94);color:#f4f4ed}
  .pet-edit-overlay{position:fixed;inset:0;z-index:999998;display:grid;place-items:center;padding:18px;background:rgba(6,14,28,.48);backdrop-filter:blur(12px)}.pet-edit-modal{width:min(560px,100%);max-height:min(760px,92vh);overflow:auto;border-radius:28px;background:var(--paper,#fbfbf7);color:var(--ink);padding:24px;box-shadow:0 34px 100px -40px rgba(0,0,0,.7)}[data-theme="dark"] .pet-edit-modal{background:#0f2139}.pet-edit-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:18px}.pet-edit-head h2{margin:4px 0 0;font-size:24px}.pet-edit-close{width:34px;height:34px;border:0;border-radius:11px;background:rgba(11,30,63,.07);color:inherit;font-size:20px;cursor:pointer}.pet-edit-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.pet-edit-grid label,.pet-edit-photo{display:grid;gap:7px;font-size:10px;font-weight:700;color:var(--muted)}.pet-edit-grid input,.pet-edit-photo input{height:46px;border:0;border-radius:14px;padding:0 14px;background:rgba(255,255,255,.72);box-shadow:inset 0 0 0 1px rgba(11,30,63,.18);color:var(--ink);font:500 12px Poppins}[data-theme="dark"] .pet-edit-grid input,[data-theme="dark"] .pet-edit-photo input{background:rgba(255,255,255,.06);color:#f4f4ed}.pet-edit-photo{margin-top:14px}.pet-edit-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:20px}.pet-edit-actions button{border:0;border-radius:999px;padding:12px 18px;font:700 11px Poppins;cursor:pointer}.pet-edit-save{background:#071f43;color:#fff}.pet-edit-cancel{background:rgba(11,30,63,.07);color:var(--ink)}[data-theme="dark"] .pet-edit-cancel{color:#f4f4ed}.pet-edit-hint{margin:8px 0 0;color:var(--muted);font-size:10px;line-height:1.5}.branddemo-ai-note{position:fixed;right:18px;bottom:18px;z-index:999999;max-width:320px;padding:11px 14px;border-radius:14px;background:#07101f;color:#fff;box-shadow:0 16px 50px -20px rgba(0,0,0,.55);font:600 11px/1.45 Poppins;animation:wagNoticeIn .22s ease both}@keyframes wagNoticeIn{from{opacity:0;transform:translateY(8px)}}
  .rail__theme{overflow:visible!important;isolation:isolate}.tg{width:21px;height:21px;display:block;overflow:visible}.tg .tg-sun-core,.tg .tg-rays,.tg .tg-moon{transform-origin:12px 12px;transition:transform .48s cubic-bezier(.22,.8,.2,1),opacity .32s ease}.tg .tg-rays{opacity:1;transform:rotate(0deg) scale(1)}.tg .tg-sun-core{opacity:1;transform:scale(1)}.tg .tg-moon{opacity:0;transform:rotate(-28deg) scale(.55)}.tg[data-theme="dark"] .tg-rays{opacity:0;transform:rotate(50deg) scale(.45)}.tg[data-theme="dark"] .tg-sun-core{opacity:0;transform:scale(.55)}.tg[data-theme="dark"] .tg-moon{opacity:1;transform:rotate(0) scale(1)}.rail__theme:hover .tg{transform:rotate(7deg)}.rail__theme .tg{transition:transform .25s ease}
  @media(max-width:620px){.pet-edit-grid{grid-template-columns:1fr}.pet-photo-edit{right:12px;top:12px}}@media(prefers-reduced-motion:reduce){.health-marquee{animation:none}.tg *{transition:none!important}}
  `;
  const st=document.createElement('style');st.id='branddemo-v26-hotfix';st.textContent=css;document.head.appendChild(st);

  function notice(text,ms=3200){document.querySelector('.branddemo-ai-note')?.remove();const n=document.createElement('div');n.className='branddemo-ai-note';n.textContent=text;document.body.appendChild(n);setTimeout(()=>n.remove(),ms)}
  function readStore(){try{return JSON.parse(localStorage.getItem(STORE_KEY)||'{}')}catch{return {}}}
  function writeStore(s){try{localStorage.setItem(STORE_KEY,JSON.stringify(s));return true}catch{return false}}
  function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

  function themeIcon(){const b=document.querySelector('.rail__theme');if(!b||b.dataset.v26icon)return;b.dataset.v26icon='1';const t=document.documentElement.dataset.theme||'light';b.innerHTML=`<svg aria-hidden="true" class="tg" data-theme="${t}" viewBox="0 0 24 24" fill="none"><g class="tg-rays" stroke="currentColor" stroke-linecap="round" stroke-width="2"><path d="M12 1.8v2M12 20.2v2M1.8 12h2M20.2 12h2M4.8 4.8l1.4 1.4M17.8 17.8l1.4 1.4M4.8 19.2l1.4-1.4M17.8 6.2l1.4-1.4"/></g><circle class="tg-sun-core" cx="12" cy="12" r="5.1" fill="currentColor"/><path class="tg-moon" d="M18.7 15.8A7.6 7.6 0 0 1 8.2 5.3 8.1 8.1 0 1 0 18.7 15.8Z" fill="currentColor"/></svg>`}
  function patchUpdates(){const p=document.querySelector('.home__promo-card');if(!p)return;p.querySelectorAll('.home__promo-label').forEach(n=>n.remove());const title=p.querySelector('.home__promo-head .bento__title');if(title){if(title.textContent!=='Updates')title.textContent='Updates';title.style.display='block'}}
  function patchHealthHome(){
    const card=document.querySelector('a.bento__card[href="/health"]');if(!card)return;
    const d=card.querySelector('.bento__desc');if(d&&d.textContent!=='Preventives and care records.')d.textContent='Preventives and care records.';
    const chips=card.querySelector('.bento__chips');if(!chips||chips.querySelector('.health-marquee-stack'))return;
    const seen=new Set(),items=[];chips.querySelectorAll('.bento__chip').forEach(chip=>{const name=chip.textContent.trim();if(!seen.has(name)){seen.add(name);items.push(chip)}});if(!items.length)return;
    const stack=document.createElement('span');stack.className='health-marquee-stack';stack.setAttribute('aria-hidden','true');
    for(let row=0;row<2;row++){
      const viewport=document.createElement('span');viewport.className='health-marquee-window';
      const track=document.createElement('span');track.className='health-marquee'+(row?' health-marquee--reverse':'');
      const ordered=row?[...items].reverse():items;
      for(let copy=0;copy<2;copy++){const group=document.createElement('span');group.className='health-marquee-group';ordered.forEach(chip=>group.appendChild(chip.cloneNode(true)));track.appendChild(group)}
      viewport.appendChild(track);stack.appendChild(viewport);
    }
    const label=document.createElement('span');label.className='sr-only';label.textContent=[...seen].join(', ');
    chips.replaceChildren(label,stack);
  }
  function patchPicker(){document.querySelectorAll('.pet-health-picker').forEach(d=>{if(d.dataset.v26)return;d.dataset.v26='1';const s=d.querySelector('summary');if(s)s.addEventListener('click',e=>{e.preventDefault();d.open=!d.open})})}
  function patchHealthModal(){const form=document.querySelector('[data-health-edit-form]');if(!form||form.dataset.v26)return;form.dataset.v26='1';let current='Other';const fixed=form.querySelector('.pet-fixed-field');if(fixed)current=fixed.querySelector('strong')?.textContent?.trim()||'Other';else if(form.querySelector('input[name="title"]'))current='Other';const label=fixed?.closest('label')||form.querySelector('input[name="title"]')?.closest('label');if(!label)return;const opts=TYPES.map(x=>`<option value="${x.replaceAll('"','&quot;')}" ${x===current?'selected':''}>${x}</option>`).join('');label.outerHTML=`<label class="pet-record-type-select-wrap">Record type<select class="pet-input pet-record-type-select" name="category">${opts}</select></label>`;const custom=document.createElement('label');custom.className='pet-record-custom';custom.innerHTML='Custom title<input class="pet-input" name="customTitle" value="">';const status=form.querySelector('input[name="status"]')?.closest('label');if(status)status.before(custom);const sel=form.querySelector('select[name="category"]'),sync=()=>custom.classList.toggle('is-visible',sel.value==='Other');sel.addEventListener('change',sync);sync()}

  function patchPetOverview(){if(location.pathname!='/pets')return;const card=document.querySelector('.pet-profile-card');if(!card||card.querySelector('[data-edit-pet-profile]'))return;card.querySelector('[data-edit-pet-photo]')?.remove();card.querySelector('[data-pet-image]')?.remove();const btn=document.createElement('button');btn.type='button';btn.className='pet-photo-edit';btn.dataset.editPetProfile='';btn.textContent='Edit pet profile';card.append(btn)}
  function openPetEditor(){const s=readStore(),name=s.activePet||'Biscuit',p=(s.pets||[]).find(x=>x.name===name);if(!p)return;document.querySelector('.pet-edit-overlay')?.remove();const ov=document.createElement('div');ov.className='pet-edit-overlay';ov.innerHTML=`<section class="pet-edit-modal" role="dialog" aria-modal="true" aria-label="Edit ${esc(p.name)} profile"><div class="pet-edit-head"><div><div class="clone-card__no">PET PROFILE</div><h2>Edit ${esc(p.name)}</h2></div><button class="pet-edit-close" type="button" data-close-pet-editor aria-label="Close">×</button></div><form data-pet-profile-form><div class="pet-edit-grid"><label>Pet name<input name="name" required maxlength="40" value="${esc(p.name)}"></label><label>Breed<input name="breed" maxlength="60" value="${esc(p.breed)}"></label><label>Age<input name="age" maxlength="30" value="${esc(p.age)}"></label><label>Weight<input name="weight" maxlength="30" value="${esc(p.weight)}"></label></div><label class="pet-edit-photo">Profile photo<input name="photo" type="file" accept="image/*"></label><p class="pet-edit-hint">Uploading a new photo will automatically create the YourBrand cartoon-style AI avatar before it replaces the current profile picture.</p><div class="pet-edit-actions"><button class="pet-edit-cancel" type="button" data-close-pet-editor>Cancel</button><button class="pet-edit-save" type="submit">Save changes</button></div></form></section>`;document.body.appendChild(ov)}
  function closePetEditor(){document.querySelector('.pet-edit-overlay')?.remove()}

  function saveHealthEdit(e){const form=e.target.closest?.('[data-health-edit-form]');if(!form||!form.dataset.v26)return;e.preventDefault();e.stopImmediatePropagation();const fd=new FormData(form),id=String(fd.get('id')||''),category=String(fd.get('category')||'Other'),state=readStore(),pet=state.activePet||'Biscuit',list=state.healthByPet?.[pet],h=Array.isArray(list)?list.find(x=>String(x.id)===id):null;if(h){h.category=category;h.title=category==='Other'?(String(fd.get('customTitle')||h.title||'Other Health Detail').trim()||'Other Health Detail'):category;h.iconName=ICONS[category]||'heart';h.status=String(fd.get('status')||'').trim()||'Not specified';h.note=String(fd.get('note')||'').trim();h.tone=String(fd.get('tone')||'neutral');writeStore(state)}location.reload()}

  function fileToSquareJpeg(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const size=768,c=document.createElement('canvas');c.width=size;c.height=size;const ctx=c.getContext('2d');ctx.fillStyle='#f4f4ed';ctx.fillRect(0,0,size,size);const scale=Math.max(size/img.width,size/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(size-w)/2,(size-h)/2,w,h);resolve(c.toDataURL('image/jpeg',.86).split(',')[1])};img.src=String(r.result)};r.readAsDataURL(file)})}
  async function generatePetAvatar(file,button){notice('AI avatars are available in a connected client app. Use a sample pet or upload a profile photo in this demo.',5000)}

  async function savePetProfile(e){const form=e.target.closest?.('[data-pet-profile-form]');if(!form)return;e.preventDefault();e.stopImmediatePropagation();const fd=new FormData(form),s=readStore(),oldName=s.activePet||'Biscuit',p=(s.pets||[]).find(x=>x.name===oldName);if(!p)return;const newName=String(fd.get('name')||oldName).trim()||oldName;p.name=newName;p.breed=String(fd.get('breed')||'').trim();p.age=String(fd.get('age')||'').trim();p.weight=String(fd.get('weight')||'').trim();if(newName!==oldName){s.activePet=newName;(s.bookings||[]).forEach(b=>{if(b.pet===oldName)b.pet=newName});if(s.healthByPet&&Object.prototype.hasOwnProperty.call(s.healthByPet,oldName)){s.healthByPet[newName]=s.healthByPet[oldName];delete s.healthByPet[oldName]}}writeStore(s);const file=fd.get('photo'),submit=form.querySelector('.pet-edit-save');if(file instanceof File&&file.size){await generatePetAvatar(file,submit)}else{closePetEditor();location.reload()}}

  let raf=0;function schedulePatch(){if(raf)return;raf=requestAnimationFrame(()=>{raf=0;themeIcon();patchUpdates();patchHealthHome();patchPicker();patchHealthModal();patchPetOverview()})}
  document.addEventListener('submit',e=>{saveHealthEdit(e);savePetProfile(e)},true);
  document.addEventListener('themechange',()=>requestAnimationFrame(()=>{const tg=document.querySelector('.rail__theme .tg');if(tg)tg.dataset.theme=document.documentElement.dataset.theme||'light'}));
  document.addEventListener('click',e=>{const edit=e.target.closest?.('[data-edit-pet-profile]');if(edit){e.preventDefault();openPetEditor();return}if(e.target.closest?.('[data-close-pet-editor]')||e.target.classList?.contains('pet-edit-overlay')){e.preventDefault();closePetEditor();return}const sw=e.target.closest?.('[data-switch-pet]');if(sw){setTimeout(()=>{const ov=document.querySelector('[data-paw-tab="overview"]');if(ov&&!ov.classList.contains('is-active'))ov.click()},0)}schedulePatch()},true);
  addEventListener('popstate',schedulePatch);
  function start(){schedulePatch();setTimeout(patchUpdates,0);setTimeout(schedulePatch,40);const main=document.getElementById('main-content');observeUI(()=>{themeIcon();patchUpdates();patchHealthHome();patchPicker();patchHealthModal();patchPetOverview()})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(start,0),{once:true});else setTimeout(start,0);
})();
